/**
 * Sveltia bundle prebuild copy.
 *
 * Copies the version-pinned Sveltia CMS bundle from
 * `node_modules/@sveltia/cms/dist/sveltia-cms.js` to
 * `static/admin/sveltia-cms.js`, where SvelteKit's static adapter
 * picks it up and serves it at `/admin/sveltia-cms.js`.
 *
 * Self-hosting (vs. a CDN `<script src>`) removes the supply-chain
 * dependency on an external host + floating semver tag. The version is
 * pinned via `package.json` devDependencies; the copied bundle is a
 * build artefact (git-ignored under `static/admin/`).
 *
 * ITS FONTS COME TOO, and they are not a nicety. Sveltia injects its own
 * <link> tags to fonts.googleapis.com for three families — Material Symbols
 * Outlined, which IS its entire icon set, plus Merriweather Sans and Noto Sans
 * Mono for its interface. The editor's CSP allows neither the stylesheet nor
 * the font file, so every icon in the editor was missing: John opened it and
 * found buttons with no symbols on them.
 *
 * Opening the CSP to Google would have fixed it in one line and undone the
 * reason this file exists. It would also have meant a request to Google every
 * time he edits his own site. So the same families are vendored here, under
 * the names Sveltia asks for, and its own <link> tags are left to be blocked:
 * by the time they fail, the faces they wanted are already loaded from disk.
 *
 * Runs as the `prebuild` lifecycle hook before `vite build`. Node 25
 * strips TypeScript types natively, so this runs as
 * `node scripts/copy-sveltia.ts` with no build step.
 */

import { copyFileSync, statSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const SRC = 'node_modules/@sveltia/cms/dist/sveltia-cms.js';
const DST = 'static/admin/sveltia-cms.js';

if (!existsSync(SRC)) {
  console.error(`prebuild: ${SRC} not found — did pnpm install run?`);
  process.exit(1);
}

mkdirSync(dirname(DST), { recursive: true });
copyFileSync(SRC, DST);

const { size } = statSync(DST);
const sizeKb = (size / 1024).toFixed(1);
console.log(`prebuild: copied Sveltia bundle (${sizeKb} KB) → ${DST}`);

/* ---------------------------------------------------------------------------
   The fonts.
   --------------------------------------------------------------------------- */

const FONT_DIR = 'static/admin/fonts';

/**
 * Latin only. Sveltia's interface is English here and John writes English; the
 * Cyrillic, Greek and Vietnamese subsets the packages ship would be about
 * 200 KB he downloads once and never renders a glyph from.
 */
interface Face {
  file: string;
  family: string;
  style: 'normal' | 'italic';
  /** A variable range, written as the two ends. */
  weight: string;
}

const FACES: Face[] = [
  {
    // The icons. One variable file carrying every symbol Sveltia draws.
    file: 'node_modules/material-symbols/material-symbols-outlined.woff2',
    family: 'Material Symbols Outlined',
    style: 'normal',
    weight: '100 700'
  },
  {
    file: 'node_modules/@fontsource-variable/merriweather-sans/files/merriweather-sans-latin-wght-normal.woff2',
    family: 'Merriweather Sans',
    style: 'normal',
    weight: '300 800'
  },
  {
    // Its real italic. The same rule the site itself follows: a browser-slanted
    // upright is not the typeface, and this one is in the box already.
    file: 'node_modules/@fontsource-variable/merriweather-sans/files/merriweather-sans-latin-wght-italic.woff2',
    family: 'Merriweather Sans',
    style: 'italic',
    weight: '300 800'
  },
  {
    file: 'node_modules/@fontsource-variable/noto-sans-mono/files/noto-sans-mono-latin-wght-normal.woff2',
    family: 'Noto Sans Mono',
    style: 'normal',
    weight: '100 900'
  }
];

mkdirSync(FONT_DIR, { recursive: true });

const css: string[] = [
  '/* Generated by scripts/copy-sveltia.ts at prebuild. Do not edit.',
  '   The families Sveltia asks Google for, served from here instead. */'
];
let fontBytes = 0;

for (const face of FACES) {
  if (!existsSync(face.file)) {
    console.error(
      `prebuild: ${face.file} not found — did pnpm install run?\n` +
        '  Without it the editor loses its icons, and it loses them SILENTLY, so this is fatal.'
    );
    process.exit(1);
  }
  const name = face.file.split('/').pop()!;
  copyFileSync(face.file, `${FONT_DIR}/${name}`);
  fontBytes += statSync(`${FONT_DIR}/${name}`).size;
  css.push(
    '@font-face {',
    `  font-family: '${face.family}';`,
    `  font-style: ${face.style};`,
    `  font-weight: ${face.weight};`,
    // `block` for the icons: a ligature rendered in a fallback face shows the
    // WORD, so "settings" appears as text until the real font lands.
    `  font-display: ${face.family.startsWith('Material') ? 'block' : 'swap'};`,
    `  src: url('/admin/fonts/${name}') format('woff2');`,
    '}'
  );
}

writeFileSync('static/admin/fonts.css', css.join('\n') + '\n');
console.log(
  `prebuild: vendored ${FACES.length} font faces (${(fontBytes / 1024).toFixed(1)} KB) → ${FONT_DIR}/, and wrote static/admin/fonts.css`
);
