/**
 * The social glyphs, written out from Simple Icons.
 *
 * Path data is not something to type by hand. Two glyphs were transcribed into
 * `SocialIcon.svelte` when there were two, and every one added that way is a
 * chance to drop a decimal in a brand mark and never notice. This reads them
 * from the `simple-icons` package — CC0, a devDependency, pinned by the
 * lockfile — and writes `src/lib/generated/social-icons.ts`.
 *
 * The OUTPUT is committed, so nothing at build time or at runtime depends on
 * the package: it is a generator run when the list changes, like the portrait
 * geometry, not a step in the build.
 *
 *     node scripts/gen-social-icons.ts
 *
 * LINKEDIN IS DELIBERATELY ABSENT from Simple Icons — LinkedIn asked to be
 * removed over trademark, and this repo is not the place to relitigate that.
 * It is still in the list below, and it is why `SocialIcon.svelte` falls back
 * to the platform's NAME rather than to nothing: a platform we have no mark
 * for still gets a working, visible link. That fallback is the general answer,
 * not a patch for one company.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import * as icons from 'simple-icons';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(root, 'src/lib/generated/social-icons.ts');

/**
 * What John can choose from, in the order the editor offers it.
 *
 * Chosen for a counsellor in the UK rather than for completeness: the ones he
 * might plausibly hold an account on, and no more, because a dropdown of forty
 * platforms is its own kind of question. WhatsApp is not here on purpose — it
 * is a way of reaching him and lives under Contact details, not a profile to
 * follow.
 */
const PLATFORMS = [
  { id: 'facebook', title: 'Facebook' },
  { id: 'instagram', title: 'Instagram' },
  { id: 'linkedin', title: 'LinkedIn' },
  { id: 'x', title: 'X' },
  { id: 'threads', title: 'Threads' },
  { id: 'bluesky', title: 'Bluesky' },
  { id: 'youtube', title: 'YouTube' },
  { id: 'tiktok', title: 'TikTok' },
  { id: 'substack', title: 'Substack' },
  { id: 'spotify', title: 'Spotify' },
  { id: 'mastodon', title: 'Mastodon' },
  { id: 'pinterest', title: 'Pinterest' }
];

const all = icons as unknown as Record<string, { title: string; path: string; slug?: string }>;
const rows: string[] = [];
const missing: string[] = [];

for (const p of PLATFORMS) {
  const key = `si${p.id[0].toUpperCase()}${p.id.slice(1)}`;
  const icon = all[key];
  if (!icon?.path) {
    missing.push(p.id);
    rows.push(`  { id: '${p.id}', title: ${JSON.stringify(p.title)}, path: null },`);
    continue;
  }
  rows.push(
    `  { id: '${p.id}', title: ${JSON.stringify(p.title)}, path: ${JSON.stringify(icon.path)} },`
  );
}

const file = `/**
 * Generated by scripts/gen-social-icons.ts. Do not edit.
 *
 * Glyph paths from Simple Icons (CC0), read from the package rather than
 * transcribed. \`path: null\` means Simple Icons carries no mark for that
 * platform; SocialIcon.svelte draws the title instead, so the link still
 * works and is still visible.
 *
 * One list, three consumers: the icons, the editor's dropdown (checked by
 * scripts/check-cms.ts against static/admin/config.yml) and the default name
 * for a profile John has not named himself.
 */
export interface SocialPlatform {
  id: string;
  title: string;
  path: string | null;
}

export const SOCIAL_PLATFORMS: SocialPlatform[] = [
${rows.join('\n')}
];

/** By id, for the renderer. */
export const SOCIAL_BY_ID: Record<string, SocialPlatform> = Object.fromEntries(
  SOCIAL_PLATFORMS.map((p) => [p.id, p])
);
`;

writeFileSync(OUT, file);
console.log(
  `gen-social-icons: wrote ${PLATFORMS.length} platform(s) → src/lib/generated/social-icons.ts` +
    (missing.length ? `\n  no mark in Simple Icons for: ${missing.join(', ')} — the name is drawn instead.` : '')
);
